# Generated by Django 5.2.7 on 2026-04-02 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('film', '0001_initial'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proiezione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora', models.DateTimeField()),
                ('prezzo_biglietto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('posti_disponibili', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proiezioni', to='film.film')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proiezioni', to='sale.sala')),
            ],
            options={
                'verbose_name': 'Proiezione',
                'verbose_name_plural': 'Proiezioni',
                'ordering': ['data_ora'],
            },
        ),
    ]
