# Generated by Django 5.2.7 on 2026-04-02 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proiezioni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biglietto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fila', models.CharField(max_length=2)),
                ('numero_posto', models.IntegerField()),
                ('stato', models.CharField(choices=[('available', 'Disponibile'), ('reserved', 'Prenotato'), ('sold', 'Venduto')], default='available', max_length=10)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data_vendita', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proiezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biglietti', to='proiezioni.proiezione')),
            ],
            options={
                'verbose_name': 'Biglietto',
                'verbose_name_plural': 'Biglietti',
                'ordering': ['numero_fila', 'numero_posto'],
                'unique_together': {('proiezione', 'numero_fila', 'numero_posto')},
            },
        ),
    ]
