# Generated by Django 5.2.7 on 2026-04-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_posti', models.IntegerField()),
                ('numero_file', models.IntegerField(default=10)),
                ('posti_per_fila', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Sale',
                'ordering': ['nome'],
            },
        ),
    ]
