# Generated by Django 5.2.7 on 2026-04-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True)),
                ('regista', models.CharField(max_length=100)),
                ('genere', models.CharField(max_length=50)),
                ('durata_minuti', models.IntegerField()),
                ('anno_uscita', models.IntegerField()),
                ('rating', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Film',
                'ordering': ['titolo'],
            },
        ),
    ]
